language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
env:
  - CASSANDRA_VERSION=1.2
  - CASSANDRA_VERSION=1.1
  - CASSANDRA_VERSION=1.0
  - CASSANDRA_VERSION=0.8
  # these two requires Java 6, see https://github.com/travis-ci/travis-ci/issues/686
  # - CASSANDRA_VERSION=0.7
  # - CASSANDRA_VERSION=0.6
before_script:
  - java -version
  - bundle exec rake 'cassandra:start[daemonize]'
